routes/web.php
<?php

use App\Http\Controllers\BorrowController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\PracticeController;
use App\Http\Controllers\ReverseController;
use App\Http\Controllers\VisitorsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('user.index');
})->name('user');


Route::get('/dashboard',[DashboardController::class,'index'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('/material',MaterialController::class);



Route::prefix('/client')->group(function (){
    Route::prefix('/mahasiswa')->group(function (){
        Route::get('/',[ClientController::class,'indexMahasiswa'])->name('client.mahasiswa.index');
        Route::get('/create',[ClientController::class,'createMahasiswa'])->name('client.mahasiswa.create');
        Route::post('/create',[ClientController::class,'storeMahasiswa'])->name('client.mahasiswa.store');
        Route::get('/{mahasiswa}/edit',[ClientController::class,'editMahasiswa'])->name('client.mahasiswa.edit');
        Route::put('/{mahasiswa}',[ClientController::class,'updateMahasiswa'])->name('client.mahasiswa.update');
        Route::delete('/{mahasiswa}',[ClientController::class,'destroyMahasiswa'])->name('client.mahasiswa.destroy');

    });
    Route::prefix('/dosen')->group(function (){
        Route::get('/',[ClientController::class,'indexDosen'])->name('client.dosen.index');
        Route::get('/create',[ClientController::class,'createDosen'])->name('client.dosen.create');
        Route::post('/create',[ClientController::class,'storeDosen'])->name('client.dosen.store');
        Route::get('/{dosen}/edit',[ClientController::class,'editDosen'])->name('client.dosen.edit');
        Route::put('/{dosen}',[ClientController::class,'updateDosen'])->name('client.dosen.update');
        Route::delete('/{dosen}',[ClientController::class,'destroyDosen'])->name('client.dosen.destroy');

    });
    Route::prefix('/instansi')->group(function (){
        Route::get('/',[ClientController::class,'indexInstansi'])->name('client.instansi.index');
        Route::get('/create',[ClientController::class,'createInstansi'])->name('client.instansi.create');
        Route::post('/create',[ClientController::class,'storeInstansi'])->name('client.instansi.store');
        Route::get('/{instansi}/edit',[ClientController::class,'editInstansi'])->name('client.instansi.edit');
        Route::put('/{instansi}',[ClientController::class,'updateInstansi'])->name('client.instansi.update');
        Route::delete('/{instansi}',[ClientController::class,'destroyInstansi'])->name('client.instansi.destroy');
    });

});
Route::prefix('/transaction')->group(function(){
    Route::resource('/borrow',BorrowController::class);
    Route::get('/borrow/edit/material/{material}/{borrow}',[BorrowController::class,'editBorrowMaterial'])->name('edit.borrow.material');
    Route::put('/borrow/edit/material/{material}/{borrow}',[BorrowController::class,'updateBorrowMaterial'])->name('update.borrow.material');
    Route::resource('/reverse',ReverseController::class);
    // Route::post('/reverse/{reverse}/approve',[ReverseController::class,'approve'])->name('wes');
    Route::post('/borrow/{borrow}/approve',[BorrowController::class,'approve'])->name('approve');
});
Route::prefix('/absensi')->group(function(){
    Route::resource('/practice',PracticeController::class);
    Route::resource('/visitor',VisitorsController::class);
    Route::post('/visitor/fetch_data', [VisitorsController::class,'fetch_data'])->name('visitor.fetch_data');
    Route::post('/visitor/create/fetch',[VisitorsController::class, 'fetch'])->name('visitor.create.fetch');
    Route::post('/practice/create/fetch',[PracticeController::class, 'fetch'])->name('practice.create.fetch');
});

resources/views/layouts/module/footer.blade.php
<footer>
    <div class="pull-right">
        Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
    </div>
    <div class="clearfix"></div>
</footer>

resources/views/layouts/module/navbar.blade.php
<div class="top_nav">
    <div class="nav_menu">
        <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>
        <nav class="nav navbar-nav">
            <ul class=" navbar-right">
                <li class="nav-item dropdown open" style="padding-left: 15px;">
                    <!-- Right Side Of Navbar -->
                    <!-- Authentication Links -->
                    @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link user-profile dropdown-toggle" href="#" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            <img src="../../design/admin/production/images/img.jpg" alt="">{{ Auth::user()->name }} <span
                                class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                               document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
                </li>
            </ul>
        </nav>
    </div>
</div>

resources/views/layouts/module/sidebar.blade.php
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <h3>General</h3>
        <ul class="nav side-menu">
            <li><a href="{{ route('dashboard') }}"><i class="fa fa-home"></i> Home <span></span></a>
            </li>
            <li><a href="{{ route('material.index') }}"><i class="fa fa-cubes"></i> Material <span></span></a>
            </li>
            <li><a><i class="fa fa-edit"></i> Absensi <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="{{ route('practice.index') }}">Absensi Praktikum</a></li>
                    <li><a href="{{ route('visitor.index') }}">Absensi Pengunjung</a></li>
                </ul>
            </li>
            <li><a><i class="fa fa-shopping-cart"></i> Transaksi <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="{{ route('borrow.index') }}">Peminjaman</a></li>
                    <li><a href="{{ route('reverse.index') }}">Pengembalian</a></li>
                </ul>
            </li>
            <li><a><i class="fa fa-users"></i> Data Client <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="{{ route('client.dosen.index') }}">Tenaga Kependidikan</a></li>
                    <li><a href="{{ route('client.mahasiswa.index') }}">Mahasiswa</a></li>
                    <li><a href="{{ route('client.instansi.index') }}">Instansi Lain</a></li>
                </ul>
            </li>
        </ul>
    </div>

</div>