routes/web.php
<?php

use App\Http\Controllers\BorrowController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\PracticeController;
use App\Http\Controllers\ReverseController;
use App\Http\Controllers\VisitorsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('user.index');
})->name('user');


Route::get('/dashboard',[DashboardController::class,'index'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('/material',MaterialController::class);



Route::prefix('/client')->group(function (){
    Route::prefix('/mahasiswa')->group(function (){
        Route::get('/',[ClientController::class,'indexMahasiswa'])->name('client.mahasiswa.index');
        Route::get('/create',[ClientController::class,'createMahasiswa'])->name('client.mahasiswa.create');
        Route::post('/create',[ClientController::class,'storeMahasiswa'])->name('client.mahasiswa.store');
        Route::get('/{mahasiswa}/edit',[ClientController::class,'editMahasiswa'])->name('client.mahasiswa.edit');
        Route::put('/{mahasiswa}',[ClientController::class,'updateMahasiswa'])->name('client.mahasiswa.update');
        Route::delete('/{mahasiswa}',[ClientController::class,'destroyMahasiswa'])->name('client.mahasiswa.destroy');

    });
    Route::prefix('/dosen')->group(function (){
        Route::get('/',[ClientController::class,'indexDosen'])->name('client.dosen.index');
        Route::get('/create',[ClientController::class,'createDosen'])->name('client.dosen.create');
        Route::post('/create',[ClientController::class,'storeDosen'])->name('client.dosen.store');
        Route::get('/{dosen}/edit',[ClientController::class,'editDosen'])->name('client.dosen.edit');
        Route::put('/{dosen}',[ClientController::class,'updateDosen'])->name('client.dosen.update');
        Route::delete('/{dosen}',[ClientController::class,'destroyDosen'])->name('client.dosen.destroy');

    });
    Route::prefix('/instansi')->group(function (){
        Route::get('/',[ClientController::class,'indexInstansi'])->name('client.instansi.index');
        Route::get('/create',[ClientController::class,'createInstansi'])->name('client.instansi.create');
        Route::post('/create',[ClientController::class,'storeInstansi'])->name('client.instansi.store');
        Route::get('/{instansi}/edit',[ClientController::class,'editInstansi'])->name('client.instansi.edit');
        Route::put('/{instansi}',[ClientController::class,'updateInstansi'])->name('client.instansi.update');
        Route::delete('/{instansi}',[ClientController::class,'destroyInstansi'])->name('client.instansi.destroy');
    });

});
Route::prefix('/transaction')->group(function(){
    Route::resource('/borrow',BorrowController::class);
    Route::get('/borrow/edit/material/{material}/{borrow}',[BorrowController::class,'editBorrowMaterial'])->name('edit.borrow.material');
    Route::put('/borrow/edit/material/{material}/{borrow}',[BorrowController::class,'updateBorrowMaterial'])->name('update.borrow.material');
    Route::resource('/reverse',ReverseController::class);
    // Route::post('/reverse/{reverse}/approve',[ReverseController::class,'approve'])->name('wes');
    Route::post('/borrow/{borrow}/approve',[BorrowController::class,'approve'])->name('approve');
});
Route::prefix('/absensi')->group(function(){
    Route::resource('/practice',PracticeController::class);
    Route::resource('/visitor',VisitorsController::class);
    Route::post('/visitor/fetch_data', [VisitorsController::class,'fetch_data'])->name('visitor.fetch_data');
    Route::post('/visitor/create/fetch',[VisitorsController::class, 'fetch'])->name('visitor.create.fetch');
    Route::post('/practice/create/fetch',[PracticeController::class, 'fetch'])->name('practice.create.fetch');
});

app/Models/Reverse.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Reverse extends Model
{
    use HasFactory;
protected $guarded = [];

public function borrow(){
    return $this->belongsTo(Borrow::class);
}
}

app/Http/Controllers/ReverseController.php
<?php

namespace App\Http\Controllers;

use App\Models\Borrow;
use App\Models\Material;
use App\Models\Reverse;
use Illuminate\Http\Request;

class ReverseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $reverses = Reverse::orderBy('created_at', 'desc')->get();
        // $borrows = Borrow::where('status'==1);
        // dd($reverses);
        return view('admin.transaction.reverse.index',compact('reverses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Reverse  $reverse
     * @return \Illuminate\Http\Response
     */
    public function show(Reverse $reverse)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Reverse  $reverse
     * @return \Illuminate\Http\Response
     */
    public function edit(Reverse $reverse)
    {
        $list = Reverse::all();
        $reverse = $list->find($reverse);
        return view('admin.transaction.reverse.edit', compact('reverse'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Reverse  $reverse
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Reverse $reverse)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Reverse  $reverse
     * @return \Illuminate\Http\Response
     */
    public function destroy(Reverse $reverse)
    {
        //
    }

    public function approve(Reverse $reverse){
        $borrow = $reverse->borrow;
        // dd($material);
        $material = $borrow->materials->first();
        Material::where('id',$material->id)->update([
            'stock' => ($material->stock + $borrow->borrowAmount)
        ]);
        Reverse::where('id',$reverse->id)->update([
            'returnAmount' => $borrow->borrowAmount,
            'notYetReturnAmount' => 0
        ]);

        Borrow::where('id',$borrow->id)->update([
            'status' => 0,
        ]);

        
        return redirect(route('reverse.index'))->with('success');
    }
}

resources/views/admin/transaction/reverse/edit.blade.php
@extends('layouts.master')
@section('title')
    Detail Pengembalian
@endsection
@section('content')
    <!-- page content -->

    <div class="">
        <div class="page-title">
            <div class="title_left mb-3">
                <label for="">Peminjam : </label>
                <h3></h3>
                {{-- @if ($borrow->client->role_id == 1)
                    <h2>Dari Mahasiswa</h2>
                @elseif ($borrow->client->role_id == 2)
                    <h2>Dari Tenaga Kependidikan</h2>
                @else
                    <h2>Dari Instansi Lain</h2>
                @endif --}}
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <!-- form input mask -->
            <div class="col">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Detail Pengembalian</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <form class="form-horizontal form-label-left" action="{{ route('reverse.update', $reverse->id) }}"
                            method="post" novalidate>
                            @method('PUT')
                            @csrf

                            <div class="field item form-group after-add-more">
                                <label class="control-label col-md-3 col-sm-3 col-xs-3">Material<span
                                        class="required">*</span></label>
                                <div class="col-md-3 col-sm-1">
                                    {{-- <input type="text" name="material" id="" disabled value="@foreach ($return->materials as $material) {{ $material->name . '(Stock: ' . $material->stock . ')' }} @endforeach"> --}}
                                    {{-- <select class="select2-single form-control " name="material" id="id">
                                        @foreach ($borrow->materials as $material)
                                            <option value="{{ $material->id }}">
                                                {{ $material->name . '(Stock: ' . $material->stock . ')' }}</option>
                                        @endforeach
                                    </select> --}}
                                </div>
                                <label class="col-form-label col-md-1 col-sm-2 label-align">Jumlah<span
                                        class="required">*</span></label>
                                <div class="col-md-2 col-sm-1">
                                    <input class="form-control" name="returnAmount" required="required" value="0" />
                                </div>
                                <button class="btn btn-success add-more" type="button">
                                    <i class="glyphicon glyphicon-plus"></i> Add
                                </button>
                            </div>
                            {{-- <div class="copy invisible">
                                <div class="field item form-group control-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-3">Material<span
                                            class="required">*</span></label>
                                    <div class="col-md-3 col-sm-1">
                                        <input type="text" name="material" id="" disabled value="@foreach ($borrow->materials as $material) {{ $material->name . '(Stock: ' . $material->stock . ')' }} @endforeach">
                                    </div>
                                    <label class="col-form-label col-md-1 col-sm-2 label-align">Jumlah<span
                                            class="required">*</span></label>
                                    <div class="col-md-2 col-sm-1">
                                        <input class="form-control" name="borrowAmount" required="required"
                                            value="{{ $borrow->borrowAmount }}" />
                                    </div>
                                    <button class="btn btn-danger remove" type="button"><i
                                            class="glyphicon glyphicon-remove"></i> Remove</button>
                                </div>
                            </div> --}}
                            <div class="ln_solid"></div>

                            <div class="form-group row">
                                <div class="col-md-9 offset-md-3">
                                    <a class="btn btn-danger" href="{{ route('reverse.index') }}">Kembali</a>
                                    <button type="submit" class="btn btn-success">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /form input mask -->
        </div>
    </div>

@endsection

resources/views/admin/transaction/reverse/index.blade.php
@extends('layouts.master')
@section('title')
    Pengembalian
@endsection
@section('content')

    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Pengembalian</h3>
            </div>
        </div>

        <div class="clearfix"></div>


        <div class="row">
            <div class="col-md-12 col-sm-12 ">
            </div>
            <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>DATA PENGEMBALIAN</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card-box table-responsive">
                                    <table id="datatable-buttons" class="table table-striped table-bordered"
                                        style="width:100%">
                                        <thead>
                                            <tr>
                                                <th scope="col">No.</th>
                                                <th scope="col">Tgl Pengembalian</th>
                                                <th scope="col">Nama Peminjam</th>
                                                <th scope="col">Jenis Barang</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($reverses as $key => $reverse)
                                                <tr>
                                                    <th scope="row">{{ $loop->iteration }}</th>
                                                    <th scope="row">{{ $reverse->created_at }}</th>
                                                    <th scope="row">{{ $reverse->borrow->client->name }}</th>
                                                    <th scope="row">{{ $reverse->materials }}</th>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection