routes/web.php
<?php

use App\Http\Controllers\BorrowController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\PracticeController;
use App\Http\Controllers\ReverseController;
use App\Http\Controllers\VisitorsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('user.index');
})->name('user');


Route::get('/dashboard',[DashboardController::class,'index'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('/material',MaterialController::class);



Route::prefix('/client')->group(function (){
    Route::prefix('/mahasiswa')->group(function (){
        Route::get('/',[ClientController::class,'indexMahasiswa'])->name('client.mahasiswa.index');
        Route::get('/create',[ClientController::class,'createMahasiswa'])->name('client.mahasiswa.create');
        Route::post('/create',[ClientController::class,'storeMahasiswa'])->name('client.mahasiswa.store');
        Route::get('/{mahasiswa}/edit',[ClientController::class,'editMahasiswa'])->name('client.mahasiswa.edit');
        Route::put('/{mahasiswa}',[ClientController::class,'updateMahasiswa'])->name('client.mahasiswa.update');
        Route::delete('/{mahasiswa}',[ClientController::class,'destroyMahasiswa'])->name('client.mahasiswa.destroy');

    });
    Route::prefix('/dosen')->group(function (){
        Route::get('/',[ClientController::class,'indexDosen'])->name('client.dosen.index');
        Route::get('/create',[ClientController::class,'createDosen'])->name('client.dosen.create');
        Route::post('/create',[ClientController::class,'storeDosen'])->name('client.dosen.store');
        Route::get('/{dosen}/edit',[ClientController::class,'editDosen'])->name('client.dosen.edit');
        Route::put('/{dosen}',[ClientController::class,'updateDosen'])->name('client.dosen.update');
        Route::delete('/{dosen}',[ClientController::class,'destroyDosen'])->name('client.dosen.destroy');

    });
    Route::prefix('/instansi')->group(function (){
        Route::get('/',[ClientController::class,'indexInstansi'])->name('client.instansi.index');
        Route::get('/create',[ClientController::class,'createInstansi'])->name('client.instansi.create');
        Route::post('/create',[ClientController::class,'storeInstansi'])->name('client.instansi.store');
        Route::get('/{instansi}/edit',[ClientController::class,'editInstansi'])->name('client.instansi.edit');
        Route::put('/{instansi}',[ClientController::class,'updateInstansi'])->name('client.instansi.update');
        Route::delete('/{instansi}',[ClientController::class,'destroyInstansi'])->name('client.instansi.destroy');
    });

});
Route::prefix('/transaction')->group(function(){
    Route::resource('/borrow',BorrowController::class);
    Route::get('/borrow/edit/material/{material}/{borrow}',[BorrowController::class,'editBorrowMaterial'])->name('edit.borrow.material');
    Route::put('/borrow/edit/material/{material}/{borrow}',[BorrowController::class,'updateBorrowMaterial'])->name('update.borrow.material');
    Route::resource('/reverse',ReverseController::class);
    // Route::post('/reverse/{reverse}/approve',[ReverseController::class,'approve'])->name('wes');
    Route::post('/borrow/{borrow}/approve',[BorrowController::class,'approve'])->name('approve');
});
Route::prefix('/absensi')->group(function(){
    Route::resource('/practice',PracticeController::class);
    Route::resource('/visitor',VisitorsController::class);
    Route::post('/visitor/fetch_data', [VisitorsController::class,'fetch_data'])->name('visitor.fetch_data');
    Route::post('/visitor/create/fetch',[VisitorsController::class, 'fetch'])->name('visitor.create.fetch');
    Route::post('/practice/create/fetch',[PracticeController::class, 'fetch'])->name('practice.create.fetch');
});

app/Models/Borrow.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Borrow extends Model
{
    use HasFactory;
    protected $guarded = [];
    public function client(){
        return $this->belongsTo(Client::class);
    }

    public function materials(){
        return $this->belongsToMany(Material::class)->withPivot('borrowAmount');
    }
}

app/Http/Controllers/BorrowController.php
<?php

namespace App\Http\Controllers;

use App\Models\Borrow;
use Illuminate\Http\Request;
use App\Models\Client;
use App\Models\Material;
use App\Models\Reverse;
use Illuminate\Support\Facades\DB;
use RealRashid\SweetAlert\Facades\Alert;

class BorrowController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {

        $borrows = Borrow::orderBy('created_at', 'desc')->get();
        return view('admin.transaction.borrow.index', compact('borrows'));
    }

    function fetch_data(Request $request)
    {

        dd($request);
        if ($request->ajax()) {
            if ($request->from_date != '' && $request->to_date != '') {
                $data = DB::table('borrow')
                    ->whereBetween('created_at', array($request->from_date, $request->to_date))
                    ->get();
            } else {
                $data = DB::table('borrow')->orderBy('created_at', 'desc')->get();
            }
            echo json_encode($data);
        }
    }


    public function create()
    {
        $clients = Client::all();

        $materials = Material::all();
        return view('admin.transaction.borrow.create', compact('clients', 'materials'));
    }


    public function store(Request $request)
    {
        $borrow = Borrow::create([
            'need' => $request->need,
            'usedIn' => $request->usedIn,
            'client_id' => $request->noId,
        ]);
        for ($i = 0; $i < count($request->material) - 1; $i++) {
            $borrow->materials()->attach($request->material[$i], ['borrowAmount' => $request->jumlah[$i]]);
            $mtl = Material::find($request->material[$i]);
            $mtl->stock = $mtl->stock - $request->jumlah[$i];
            $mtl->save();
        }
        toast('Data Peminjaman', 'Berhasil Ditambahkan');
        return redirect(route('borrow.index'));


    }

    public function show(Borrow $borrow)
    {
        $list = Borrow::all();
        $borrow = $list->find($borrow);
        return view('admin.transaction.borrow.show', compact('borrow'));
    }

    public function editBorrowMaterial(Material $material, Borrow $borrow)
    {

        return view('admin.transaction.borrow.edit', compact('borrow', 'material'));
    }

    public function updateBorrowMaterial(Request $request, Material $material, Borrow $borrow)
    {
        if (($material->stock - $request->jumlah) >= 0 && $request->jumlah >= 0) {
            $borrowAmountUpdate = ($material->stock + $request->jumlahOld) - $request->jumlah;
            $borrow->materials()->updateExistingPivot($material->id, ['borrowAmount' => $request->jumlah]);

            Material::where('id', $material->id)->update([
                'stock' => $borrowAmountUpdate
            ]);

            Alert::success('Success', 'Jumlah pinjaman berhasil diupdate');
            return redirect()->back();
        }
        Alert::warning('Warning', 'Jumlah Pinjaman Melebihi Stok Barang');
        return redirect()->back();
    }

    public function destroy(Borrow $borrow)
    {
        if ($borrow->status == 0) {
            # code...
            $borrow = Borrow::find($borrow->id);
            $borrow->delete();
            Alert::success('Success', 'Loan has been deleted');
            return redirect(route('borrow.index'));
        } else {
            Alert::warning('Warning', 'The refund has not been approved');
            return redirect(route('borrow.index'));
        }
    }

    public function approve(Borrow $borrow)
    {
        $mtl = $borrow->materials->all();
        $mate = '';

        foreach ($borrow->materials as $key => $bm) {
            $mate .= $bm->name . ', ';
        }
        $reverse = Reverse::create([
            'borrow_id' => $borrow->id,
            'materials' => $mate
        ]);

        for ($i = 0; $i < count($mtl); $i++) {

            $m = Material::find($borrow->materials[$i]->id);
            $m->stock = $m->stock + $borrow->materials[$i]->pivot->borrowAmount;
            $m->save();
        }

        Borrow::where('id', $borrow->id)->update([
            'status' => 0
        ]);
        Alert::success('Success', 'Loan has been approved');

        return redirect(route('reverse.index'))->with('success');
    }
}

resources/views/admin/transaction/borrow/create.blade.php
@extends('layouts.master')
@section('content')


    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Tambah Peminjaman</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Tambah Peminjaman</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <form action="{{ route('borrow.store') }}" method="POST" novalidate>
                            @csrf
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">No. Identitas<span
                                        class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <select class="form-control select2-single" name="noId" id="noId">
                                        @foreach ($clients as $client)
                                            <option value="{{ $client->id }}">
                                                {{ $client->noId . ' - ' . $client->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="field item form-group after-add-more">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Material<span
                                        class="required">*</span></label>
                                <div class="col-md-3 col-sm-1">
                                    <select class="select2-single form-control " name="material[]" id="id">
                                        @foreach ($materials as $material)
                                            <option value="{{ $material->id }}">
                                                {{ $material->name . '(Stock: ' . $material->stock . ')' }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <label class="col-form-label col-md-1 col-sm-2  label-align">Jumlah<span
                                        class="required">*</span></label>
                                <div class="col-md-2 col-sm-1">
                                    <input class="form-control" type="number" min=1 data-validate-length-range="6"
                                        name="jumlah[]" required="required" />
                                </div>
                                <button class="btn btn-success add-more" type="button">
                                    <i class="glyphicon glyphicon-plus"></i> Add
                                </button>
                            </div>
                            <div class="copy invisible">
                                <div class="field item form-group control-group">
                                    <label class="col-form-label col-md-3 col-sm-3  label-align">Material<span
                                            class="required">*</span></label>
                                    <div class="col-md-3 col-sm-1">
                                        <select class="select2-single form-control " name="material[]" id="id">
                                            @foreach ($materials as $material)
                                                <option value="{{ $material->id }}">
                                                    {{ $material->name . '(Stock: ' . $material->stock . ')' }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <label class="col-form-label col-md-1 col-sm-2  label-align">Jumlah<span
                                            class="required">*</span></label>
                                    <div class="col-md-2 col-sm-1">
                                        <input class="form-control" type="number" min=1 data-validate-length-range="6"
                                            name="jumlah[]" required="required" />
                                    </div>
                                    <button class="btn btn-danger remove" type="button"><i
                                            class="glyphicon glyphicon-remove"></i> Remove</button>
                                </div>
                            </div>

                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Keperluan<span
                                        class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <input class="form-control" data-validate-length-range="6" data-validate-words="2"
                                        name="need" required="required" />
                                </div>
                            </div>
                            <div class="field item form-group">
                                <label class="col-form-label col-md-3 col-sm-3  label-align">Digunakan
                                    di<span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6">
                                    <input class="form-control" data-validate-length-range="6" data-validate-words="2"
                                        name="usedIn" required="required" />
                                </div>
                            </div>
                            <div class="ln_solid">
                                <div class="form-group">
                                    <div class="col-md-6 offset-md-3 text-right">
                                        <a href="{{ route('borrow.index') }}" class="btn btn-danger btn-xs"><i
                                                class="fa fa-mail-reply"></i>
                                            Back
                                        </a>
                                        <button type='submit' class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/transaction/borrow/edit.blade.php
@extends('layouts.master')
@section('title')
    Detail Peminjaman
@endsection
@section('content')
    <!-- page content -->

    <div class="">
        <div class="page-title">
            <div class="title_left mb-3">
                <label for="">Peminjam : </label>
                <h3>{{ $borrow->client->name }} : {{ $borrow->client->noId }}</h3>
                @if ($borrow->client->role_id == 1)
                    <h2>Dari Mahasiswa</h2>
                @elseif ($borrow->client->role_id == 2)
                    <h2>Dari Tenaga Kependidikan</h2>
                @else
                    <h2>Dari Instansi Lain</h2>
                @endif
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <!-- form input mask -->
            <div class="col">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Detail Peminjaman</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <form class="form-horizontal form-label-left"
                            action="{{ route('update.borrow.material', ['material' => $material, 'borrow' => $borrow]) }}"
                            method="post" novalidate>
                            @method('PUT')
                            @csrf
                            <div class="form-group row">
                                <label class="control-label col-md-3 col-sm-3 col-xs-3">Nama Barang</label>
                                <div class="col-md-9 col-sm-9 col-xs-9">
                                    <input type="text" class="form-control" value="{{ $material->name . ' {' . $material->stock . '} ' }}" disabled>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-md-3 col-sm-3 col-xs-3">Jumlah Peminjaman</label>
                                <div class="col-md-9 col-sm-9 col-xs-9">
                                    <input type="number" min=1 class="form-control" name="jumlah" @foreach ($borrow->materials as $m)  @if ($material->id==$m->id)
                                    value={{ $m->pivot->borrowAmount }} @endif
                                    @endforeach >
                                    <input type="hidden" min=1 class="form-control" name="jumlahOld" @foreach ($borrow->materials as $m)  @if ($material->id==$m->id)
                                    value={{ $m->pivot->borrowAmount }} @endif
                                    @endforeach >
                                </div>
                            </div>
                            <div class="ln_solid"></div>

                            <div class="form-group row">
                                <div class="col-md-9 offset-md-3">
                                    <a href="{{ route('borrow.show', ['borrow' => $borrow]) }}"
                                        class="btn btn-danger btn-xs"><i class="fa fa-mail-reply"></i>
                                        Back
                                    </a>
                                    <button type="submit" class="btn btn-success">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /form input mask -->
        </div>
    </div>

@endsection

resources/views/admin/transaction/borrow/show.blade.php
@extends('layouts.master')
@section('title')
    Detail Peminjaman
@endsection
@section('content')

    <!-- page content -->
    <div class="">
        <div class="page-title">
            <div class="title_left">
                @if ($borrow->client->role_id == 1)
                    <h3>Dari Mahasiswa</h3>
                @elseif ($borrow->client->role_id == 2)
                    <h3>Dari Tenaga Kependidikan</h3>
                @else
                    <h3>Dari Instansi Lain</h3>
                @endif

                <div class="title_left mb-3">
                    <label for="">Detail Peminjam : </label>
                    <h4>{{ $borrow->client->name }}</h4>
                    <h4>: {{ $borrow->client->noId }}</h4>

                </div>
            </div>
            <div class="title_right" style="float: right">


            </div>
            <div class="title_right mb-3">
                <div class="col-sm-12 mt-3 text-right">
                    <a href="{{ route('borrow.index') }}" class="btn btn-danger btn-xs"><i class="fa fa-mail-reply"></i>
                        Back
                    </a>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                    <div class="x_title">
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group row">
                                </div>
                                <div class="card-box table-responsive">
                                    <table id="datatable" class="table table-striped table-bordered" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th scope="col">No</th>
                                                <th scope="col">Jenis Barang</th>
                                                <th scope="col">Jumlah yang dipinjam</th>
                                                <th scope="col">Status</th>
                                                <th scope="col">Aksi</th>
                                            </tr>
                                        </thead>


                                        <tbody>
                                            @foreach ($borrow->materials as $material)
                                                <tr>
                                                    <th scope="row">{{ $loop->iteration }}</th>
                                                    <th scope="row">{{ $material->name }}</th>
                                                    <th scope="row">{{ $material->pivot->borrowAmount }}</th>

                                                    <th scope="row">
                                                        @if ($material->pivot->borrowAmount != 0)
                                                            Masih dipinjam
                                                        @else
                                                            Sudah dikembalikan
                                                        @endif
                                                    </th>
                                                    <th scope="row">
                                                        <form action="{{ route('borrow.destroy', $borrow->id) }}"
                                                            method="post">
                                                            @csrf
                                                            @method('delete')
                                                            <button type="submit" class="btn btn-danger"><i
                                                                    class="fa fa-trash"></i> Hapus </button>
                                                        </form>
                                                        <a href="{{ route('edit.borrow.material', ['material' => $material, 'borrow' => $borrow]) }}"
                                                            class="btn btn-info btn-xs"><i class="fa fa-info-circle"></i>
                                                            Edit
                                                        </a>
                                                    </th>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>>
    </div>
    <!-- /page content -->

@endsection